apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    app: hello-world-pod
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-world-pod
